### ISSUE TITLE
Gameplay Decision - Should we make score increase even more for larger drops?

### ISSUE THREAD

**Issue by daveydave60** [daveydave60/Raindrops#10]
Right now the score is based on the radius of each clicked drop.  This means you get more points for clicking two of the smallest drops than for clicking one drop that has combined from two.  I don't love this dynamic.  It should be the other way around.

**Comment by djweissenborn** [comment]
I agree, score should be based on area, possibly with some sauce on top.

**Comment by daveydave60** [comment]
How about Area^1.2 ?

**Comment by djweissenborn** [comment]
I was thinking something like a breakpoint to incentive waiting, or
triangular growth.

**Comment by daveydave60** [comment]
Interesting. How would the breakpoint work?

**Comment by djweissenborn** [comment]
Just like, you get an extra point after 10, 2 above 20, something like that.

**Comment by daveydave60** [comment]
Ok yeah. The magnitude of the extra points will probably need to be chosen with some caution. Now that you also get points for every drop that your clicked drop hits along the way down, the user is more likely to just want to click a bunch of stuff up at the top and not wait. I'd like the collision points to be meaningful, but at the same time make it so that rapid-fire clicking will never get you the high score. Or maybe I'm trying to make this type of game too strategic and it's fine to just leave it where rapid-fire is optimal?  What do you think?

**Comment by daveydave60** [comment]
Decided to simplify this.  Most of the time small drops will be worth nothing, except under certain rare circumstances where their worth will be equal to their radius.  Under these rare circumstances (for example the special tornado icon was clicked), we are ok with the fact that smaller drops are worth more than their relative area would suggest.
